language: ruby
rvm:
  - 2.2.2
  - 2.1.5
  - 2.0.0
script: bundle exec rake
sudo: false
before_install:
  - gem update --system
services:
  - redis-server
notifications:
  email:
    - andrew.kreps@gmail.com
